
// Packages -----------------------------------------------------------------------------
import type { Metadata } from "next";
// Fonts --------------------------------------------------------------------------------
import { Geist, Geist_Mono } from "next/font/google";
// Styles -------------------------------------------------------------------------------
import "../styles/globals.css";



//______________________________________________________________________________________
// ===== Fonts =====

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});



//______________________________________________________________________________________
// ===== Metadata =====

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};



//______________________________________________________________________________________
// ===== Component =====

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    //______________________________________________________________________________________
    // ===== Component Return =====
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
