const a = {
    linMcton: {
        key: "linMcton",
        display: "Lin Mcton",
        innateRole: "tech",
        innateSubRole: "corpo",
        roleLevels: {
            corpo: 4,
            solo: 1,
            tech: 5,
        },
        xp: 125,
    },
    antikytheraFrost: {
        key: "antikytheraFrost",
        display: "Antikythera Frost",
        innateRole: "tech",
        innateSubRole: "corpo",
        roleLevels: {
            corpo: 2,
            solo: 0,
            tech: 3,
        },
        xp: 0,
    },
    bearMae: {
        key: "bearMae",
        display: "Bear Mae",
        innateRole: "solo",
        innateSubRole: "tech",
        roleLevels: {
            corpo: 0,
            solo: 3,
            tech: 2,
        },
        xp: 0,
    },
    avaProan: {
        key: "avaProan",
        display: "Ava Proan",
        innateRole: "tech",
        innateSubRole: "solo",
        roleLevels: {
            corpo: 0,
            solo: 2,
            tech: 3,
        },
        xp: 0,
    },
    lanSpokesan: {
        key: "lanSpokesan",
        display: "Lan Spokesan",
        innateRole: "tech",
        innateSubRole: "corpo",
        roleLevels: {
            corpo: 2,
            solo: 0,
            tech: 3,
        },
        xp: 0,
    },
    lelaButaite: {
        key: "lelaButaite",
        display: "Lela Butaite",
        innateRole: "solo",
        innateSubRole: "tech",
        roleLevels: {
            corpo: 0,
            solo: 3,
            tech: 2,
        },
        xp: 0,
    },
    radiaBarajas: {
        key: "radiaBarajas",
        display: "Radia Barajas",
        innateRole: "solo",
        innateSubRole: "corpo",
        roleLevels: {
            corpo: 2,
            solo: 3,
            tech: 0,
        },
        xp: 0,
    },
    teraBlackley: {
        key: "teraBlackley",
        display: "Tera Blackley",
        innateRole: "corpo",
        innateSubRole: "solo",
        roleLevels: {
            corpo: 3,
            solo: 2,
            tech: 0,
        },
        xp: 0,
    },
    katushaDanson: {
        key: "katushaDanson",
        display: "Katusha Danson",
        innateRole: "tech",
        innateSubRole: "solo",
        roleLevels: {
            corpo: 0,
            solo: 3,
            tech: 5,
        },
        xp: 45,
    },
    leeChower: {
        key: "leeChower",
        display: "Lee Chower",
        innateRole: "corpo",
        innateSubRole: "solo",
        roleLevels: {
            corpo: 4,
            solo: 2,
            tech: 0,
        },
        xp: 5,
    },
};
